// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.l.codeing.Dagger2.sourcecode;


import dagger.internal.Factory;

public enum Weapon_Factory implements Factory<Weapon> {
  INSTANCE;

  @Override
  public Weapon get() {
    return new Weapon();
  }

  public static Factory<Weapon> create() {
    return INSTANCE;
  }
}
